### ISSUE TITLE
[Result-list] Formatting of attributes

### ISSUE THREAD

**Issue by antoniave** [open-pioneer/trails-openlayers-base-packages#241]
As a user I want to see the attributes in an appropriate format. 

Acceptance criteria:
- numbers: "Intl formatNumber" is used to show correct separators depending on the language
  - the number of decimal places can be configured globally (for all attributes in the list)  
- dates: will be rendered as actual dates in the time zone of the user 
  - the used date-formatter (Intl.DateTimeFormatOptions) can be configured globally (for all attributes in the list)  
- boolean: will be rendered as meaningful strings ("JA"/"NEIN" or "YES"/"NO")
- custom cell renderer: The interface for loading data into the result-list can take metadata for the column headers (e.g. attribute name, display name, column width). The metadata must extended to also take a custom cell renderer for a column. The renderer is used to render content of the cells of the column. 
- invalid values like "NaN" and "null" should be shown as empty cells

**Comment by mbeckem** [comment]
- For numbers and dates: simply use `intl.formatNumber` / `intl.formatDate`.
  -  add two new (optional) properties to the result list to provide intl number / date options. These can be passed as a second argument to the `intl` methods
- Boolean: `intl.formatMessage(...)`
- Cell renderer: Add an optional `renderCell` to the column in the result list's metadata. If this property is defined, just call it and return its result to render the cell's content. Otherwise, use default behavior (toString / number / date / boolean ...)
